FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY producer.py producer.py
COPY config.properties config.properties

CMD ["python", "producer.py"]
